[package]
name = "checks"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
hickory-resolver = "0.25.2"
ping-rs = "0.1.2"
reqwest = { version = "0.12.4", features = ["json"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
ssl-exp = { path = "../ssl-exp" }
tokio = { version = "1.37.0", features = ["net", "rt", "time"] }
tracing = "0.1.40"

[dev-dependencies]
axum = "0.8.1"
openssl = "0.10.66"
tokio = { version = "1.37.0", features = ["macros", "rt-multi-thread"] }
