# Cargo config file.
# See: https://doc.rust-lang.org/cargo/reference/config.html

# Environments variables set for all `cargo ...` commands.
[env]
# Web static assets
ASSETS_PATH="./frontend/build/"

# Scope down tracing, to filter out external lib tracing.
RUST_LOG="server=debug,worker=debug,tower_http=trace"

# Path to store data
DATA_PATH="./data"

# Generate from: openssl rand -base64 48
JWT_SECRET="A_very_secure_secret"

# for testing
DATABASE_URL="sqlite://data/test.db"