use std::process::Command;

// generated by `sqlx migrate build-script`
fn main() {
    // trigger recompilation when a new migration is added
    println!("cargo:rerun-if-changed=migrations");

    // Set version env
    let output = Command::new("git")
        .args(["describe", "--tags"])
        .output()
        .expect("git command not found.");
    if output.status.success() {
        println!(
            "cargo:rustc-env=STAMON_VERSION={}",
            String::from_utf8_lossy(&output.stdout)
        );
    }
}
