name: Build and deploy GH Pages


on:
  push:
    branches:
      - main
    paths:
      - 'landing/**'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.17.2
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          BUILD_DIR: ./landing
          TOKEN: ${{ secrets.GITHUB_TOKEN }}